<?php 
/**
 *  @file
 * This file demonstrates how to use hook functions
 */


 /**
  * Impliment hook cron
  */
function first_custom_module_cron() {
    \Drupal::messenger()->addMessage(t("HEllo this is the first hook"));
}


/**
 * Impliment form_alter_hook
 */
function first_custom_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
   if($form_id == 'node_article_edit_form'){
       $form['actions']['submit']['#value'] = t("Save kardu sir?");
   }
   if($form_id =='node_page_edit_form'){
    $form['actions']['submit']['#value'] = t("Aur kitne banaega bhai?");
   }
}

/**
 * Implement hook_help 
 */
 function first_custom_module_help($path, $arg){
    if($path == 'admin/help#first_custom_module'){
        return t("Koi help nhi milega..khud se karo!!");
    }
 }