<?php

/**
 * @file
 * This file demonstrates how to use hook functions.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_cron().
 */
function hook_module_cron() {
  \Drupal::messenger()->addMessage(t("Hello this is the first hook"));
}

/**
 * Implements hook_form_alter().
 *
 * Used to alter the form structure value.
 */
function hook_module_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_article_edit_form') {
    $form['actions']['submit']['#value'] = t("Save kardu sir?");
  }
  if ($form_id == 'node_page_edit_form') {
    $form['actions']['submit']['#value'] = t("Aur kitne banaega bhai?");
  }
}

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 */
function hook_module_help($path, $arg) {
  if ($path == 'admin/help#first_custom_module') {
    return t("Koi help nhi milega..khud se karo!");
  }
}
